In [4]:
import numpy as np
import math

In [10]:
a = np.array([1, 2, 3])
print(a)
print(a.ndim)

[1 2 3]
1


In [11]:
d = np.zeros((2, 3))
print(d)

e = np.ones((2, 3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
f = np.arange(10, 50, 2)
f

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [13]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

c = a - b
print(c)

d = a * b
print(d)

[ 9 18 27 36]
[ 10  40  90 160]


In [14]:
farenheit = np.array([0, -10, -5, -15, 0])

celcius = (farenheit - 31) * (5/9)
celcius

array([-17.22222222, -22.77777778, -20.        , -25.55555556,
       -17.22222222])

In [15]:
celcius > -20

array([ True, False, False, False,  True])

In [16]:
celcius % 2 == 0

array([False, False,  True, False, False])

In [19]:
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])
print(A * B)
print(A @ B)


[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
